### ISSUE TITLE
VRChat上のfavoriteフォルダ一覧がデフォルトで見えると嬉しい

### ISSUE THREAD

**Issue by Narazaka** [Raifa21/VRC-Worlds-Manager#3]
VRC内での操作はなんだかんだそちらのほうがはやいので

**Comment by Raifa21** [comment]
初期起動時にVRChatと同じように4個のフォルダが並ぶ状態、という認識で大丈夫でしょうか？

**Comment by Narazaka** [comment]
![image](https://github.com/user-attachments/assets/b0d80c53-10fa-4bd4-bf82-01b023384253)
ここにすでに4つ表示されてるイメージですね

**Comment by Raifa21** [comment]
検討させていただきます。
